# since nasm and asm are not in white list
# undo for container-based build
sudo: required

language: cpp

compiler:  
    - gcc
    - clang

# since nasm and asm are not in white list
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y yasm nasm

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

# cmake 3: https://github.com/travis-ci/travis-ci/issues/4631
addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    - nasm
#    - yasm
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
    - cmake
    - cmake-data
    - libboost1.55-all-dev

before_script:  
    - cd externals/x264
# since nasm and asm are not in white list
# disabling asm since yasm isn't in apt sources whitelist
    - ./configure --disable-asm
# yasm version on precise is too old
#    - ./configure
    - make
    - cd -
    - cd externals/openh264
#    - ./configure
    - make
    - cd -
    - mkdir build
    - cd build
    - cmake ../src

script: make  

